workflows:
  ios-ipa:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
