workflows:
  ios-workflow:
    name: Build iOS IPA
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          pod install --project-directory=ios
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/Runner.app
      - build/ios/iphoneos/Runner.ipa
    publishing:
      email:
        recipients:
          - bonettiale07@gmail.com
